### ISSUE TITLE
undefined method `bytesize'

### ISSUE THREAD

**Issue by szymonbaranowski** [solarisBank/idnow-client#43]
Hi, I'm following your example in Readme and with valid PDF file this is what is happening when I'm trying to hit `client.upload_identification_document`:

`NoMethodError: undefined method 'bytesize' for #<File:tmp/sample-document.pdf>
Did you mean?  bytes`

Any ideas?

**Comment by JoanMartinezRipoll** [comment]
Hi,
The method is expecting some data, not a File object. Try reading the data from the File.

You can check the upload_identification_document_spec for a working example
https://github.com/solarisBank/idnow-client/blob/master/spec/integration/upload_identification_document_spec.rb

Let me know if that helps
